//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sentiment.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int Id { get; set; }
        public string FeedbackType { get; set; }
        public string FeedbackOn { get; set; }
        public string StaffServed { get; set; }
        public string Branch { get; set; }
        public string FeedbackText { get; set; }
        public Nullable<double> SentimentScore { get; set; }
        public string Sentiment { get; set; }
        public int CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
